name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    env:
      key1: ${{secrets.GITHUB_TOKEN}}
      if: $key1 != null
      run: echo "running
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Semantic Release  ${{secrets.GITHUB_TOKEN}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Referência ao segredo configurado no repositório
        run: npx semantic-release
